from typing import Optional, List, Tuple, Any, Dict
from ragen.env.base import BaseLanguageBasedEnv
import random
import gymnasium as gym
import pandas as pd
import re
from rouge_score import rouge_scorer
import json

class MedicalConsultationEnv(BaseLanguageBasedEnv, gym.Env):
    """
    A medical consultation environment where a doctor (policy model) interacts with a patient (fixed LLM).
    The doctor asks questions and makes a diagnosis, while the patient responds based on their condition.
    The patient's responses are generated by an external LLM and passed to the environment.
    """

    INVALID_ACTION = "No question."

    def __init__(self, parquet_path: str):
        """
        Initialize the environment for Countdown Problem

        Args:
            train_path: Path to the train parquet file
            test_path: Path to the test parquet file
        """
        BaseLanguageBasedEnv.__init__(self)
        self.data, self.seed_to_index = self._get_data_from_parquet(parquet_path)
        self.parquet_path = parquet_path
        self.conversation_history = []
        self.diagnosis_made = False
        self.max_turns = 5  # Maximum number of questions allowed
        self.index = None # index of the data
        self.candidate_questions = None # candidate questions (from the gt)
        self.visited_questions = [] # visited questions
        self.rouge_scorer = rouge_scorer.RougeScorer(['rougeL'], use_stemmer=True) 

    @staticmethod
    def _get_data_from_parquet(path: str):
        """
        Get data from parquet file and create mapping.

        Args:
            path: Path to the parquet file containing the data

        Returns:
            tuple: (data, mapping) where
                data: List of dicts containing target and numbers for each problem
                mapping: Dict mapping original indices to new sequential indices

        The function:
        1. Reads the parquet file
        2. Extracts target numbers and available numbers for each problem
        3. Creates an index mapping to maintain reference to original data
        """
        df = pd.read_parquet(path)
        
        # Extract target and numbers for each problem
        data = []
        for item in df.reward_model.values[:200]:
            d = json.loads(item)
            data.append(
                {
                    'target': d['ground_truth'],
                    'patient_information': d['patient_information']
                }
            )

        # Create mapping from original indices to sequential indices
        original_indices = [item['index'] for item in df.extra_info.values]
        seed_to_index = {orig_idx: new_idx for new_idx, orig_idx in enumerate(original_indices)}
        
        return data, seed_to_index
    
    
    def reset(self, seed: int = None) -> str:
        """Reset the environment and reward distributions"""
        gym.Env.reset(self, seed=seed)
            
        # Reset tracking variables
        self._reset_tracking_variables()
        self.index = self.seed_to_index[seed]
        self.candidate_questions = self.data[self.index]['patient_information']
        self.visited_questions = [] # index of the visited questions
        return self.render()
    
    def step(self, action: str, patient_response: str) -> Tuple[str, float, bool, Dict]:
        """
        Execute one step in the environment.
        
        Args:
            action: The doctor's question or diagnosis
            patient_response: The patient's response generated by external LLM
            
        Returns:
            observation (rendered environment), reward, done, info
        """
        if self.diagnosis_made:
            return self.render(), 0, True, {"action_is_effective": False}
        
        reward = -0.5 # Penalty for each turn
            
        # Check if the action is a diagnosis: Setting a special tag to indicate the action is a diagnosis <diagnosis>xxx</diagnosis>; Match the tag and extract the diagnosis
        if "<diagnosis>" in action:
            # Match the tag and extract the diagnosis
            diagnosis = re.search(r"<diagnosis>(.*?)</diagnosis>", action).group(1)
            self.diagnosis_made = True
            # GT diagnosis
            gt_diagnosis = self.data[self.index]['target']['诊断'] # TODO: change to the unified format
            # Calculate the longest common subsequence between the diagnosis and the gt_diagnosis
            rouge += self._get_rouge_score(diagnosis, gt_diagnosis)
            reward = rouge * 10 # Scale the reward to 10

            # GT Suggestion
            gt_suggestion = self.data[self.index]['target']['建议'] # TODO: change to the unified format
            if len(gt_suggestion) > 0:
                suggestion = re.search(r"<suggestion>(.*?)</suggestion>", action).group(1)
                rouge += self._get_rouge_score(suggestion, gt_suggestion)
                reward += rouge * 10 # Scale the reward to 10 (maybe leverage llm to calculate the similarity is better)

            return self.render(), reward, True, {"action_is_effective": True}
        
        # Check the patient's response, <question_id>xxx</question_id>; Match the tag and extract the question_id   
        if "<question_id>" in patient_response:
            question_id = re.search(r"<question_id>(.*?)</question_id>", patient_response).group(1)
            if question_id not in self.visited_questions:
                self.visited_questions.append(question_id)
                reward += 1
            else:
                reward -= 1 # repeat the question
        else:
            reward -= 0.5 # not a valid question
            
        # Process as a question
        if len(self.conversation_history) >= self.max_turns:
            return self.render(), -1, True, {"action_is_effective": False}
            
        # Add the conversation to history
        self.conversation_history.append({"Doctor": action, "Patient": patient_response})
        
        return self.render(), reward, False, {"action_is_effective": True}
    
    def render(self, mode: str = 'tiny_rgb_array') -> str:
        """
        Render the current state of the environment.
        """
        if mode != 'tiny_rgb_array':
            raise ValueError(f"Unsupported render mode: {mode}")
            
        output = "Medical Consultation:\n\n"
        
        # Add conversation history
        for turn in self.conversation_history:
            output += f"Doctor: {turn['Doctor']}\n"
            output += f"Patient: {turn['Patient']}\n"

        return output
    
    def success(self) -> bool:
        """
        Check if the diagnosis was correct.
        """
        if not self.diagnosis_made:
            return False
        return self.reward >= 10
    
    def finished(self) -> bool:
        """
        Check if the consultation is finished.
        """
        return self.diagnosis_made or len(self.conversation_history) >= self.max_turns
    
    def copy(self) -> 'MedicalConsultationEnv':
        """
        Create a deep copy of the environment.
        """
        new_env = MedicalConsultationEnv(self.parquet_path)
        new_env.conversation_history = self.conversation_history.copy()
        new_env.diagnosis_made = self.diagnosis_made
        new_env.candidate_questions = self.candidate_questions
        new_env.visited_questions = self.visited_questions
        new_env.index = self.index

        self._copy_tracking_variables(new_env)
        return new_env
    
    def extract_action(self, text: str) -> str:
        """
        Extract action from text input.
        """
        return text.strip() 
    
    def _get_rouge_score(self, str1: str, str2: str) -> float:
        """
        Calculate the ROUGE score between two strings.
        """
        score = self.rouge_scorer.score(str1, str2)
        return score['rougeL'].recall  # 可选 precision, recall, fmeasure
        

if __name__ == "__main__":
    env = MedicalConsultationEnv(parquet_path="data/medical_consultation/train.parquet")
    env.reset(seed=0)
    obv, reward, done, info = env.step("你好，请问你哪里不舒服？", "<question_id>1</question_id>")
    print(obv)
    print(reward)
    print(done)
    print(info)
